---
resources:
- git@github.com:kuberik/genres//ci/make

patchesStrategicMerge:
- screener-config.yaml

namePrefix: engine-
namespace: kuberik-ci

images:
  - &image_template
    name: clone
    newName: golang
    newTag: "1.15"
  - <<: *image_template
    name: build
  - <<: *image_template
    name: test
