---
resources:
- ci-movie.yaml

configMapGenerator:
- name: engine-ci-scripts
  files:
  - github-status-update.sh
  - git-clone.sh
  - kaniko-publish.sh

generatorOptions:
  disableNameSuffixHash: true

namespace: kuberik-ci
